CREATE TABLE `financial_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractId` int NOT NULL,
	`propertyId` int NOT NULL,
	`ownerId` int NOT NULL,
	`type` enum('recebimento_aluguel','repasse_proprietario','comissao_imobiliaria','despesa_imovel','multa','taxa_extra') NOT NULL,
	`amount` int NOT NULL,
	`referenceMonth` varchar(7) NOT NULL,
	`dueDate` timestamp NOT NULL,
	`paymentDate` timestamp,
	`status` enum('pendente','pago','atrasado','cancelado') NOT NULL DEFAULT 'pendente',
	`paymentMethod` enum('pix','transferencia','boleto','dinheiro','cartao'),
	`description` text,
	`notes` text,
	`receiptUrl` varchar(500),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	CONSTRAINT `financial_transactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `property_expenses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`contractId` int,
	`expenseType` enum('manutencao','reparo','pintura','limpeza','iptu','condominio','seguro','taxa_administracao','outros') NOT NULL,
	`amount` int NOT NULL,
	`expenseDate` timestamp NOT NULL,
	`paidBy` enum('proprietario','inquilino','imobiliaria') NOT NULL,
	`description` text NOT NULL,
	`notes` text,
	`receiptUrl` varchar(500),
	`status` enum('pendente','pago','cancelado') NOT NULL DEFAULT 'pendente',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	CONSTRAINT `property_expenses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `property_owners` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`documentType` enum('cpf','cnpj') NOT NULL,
	`documentNumber` varchar(20) NOT NULL,
	`email` varchar(320),
	`phone` varchar(20),
	`whatsapp` varchar(20),
	`address` text,
	`city` varchar(100),
	`state` varchar(2),
	`zipCode` varchar(10),
	`bankName` varchar(100),
	`bankAgency` varchar(20),
	`bankAccount` varchar(30),
	`bankAccountType` enum('corrente','poupanca'),
	`pixKey` varchar(255),
	`notes` text,
	`active` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	CONSTRAINT `property_owners_id` PRIMARY KEY(`id`),
	CONSTRAINT `property_owners_documentNumber_unique` UNIQUE(`documentNumber`)
);
--> statement-breakpoint
CREATE TABLE `rental_contracts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`propertyId` int NOT NULL,
	`ownerId` int NOT NULL,
	`tenantId` int NOT NULL,
	`contractNumber` varchar(50),
	`startDate` timestamp NOT NULL,
	`endDate` timestamp NOT NULL,
	`rentAmount` int NOT NULL,
	`condoFee` int DEFAULT 0,
	`iptu` int DEFAULT 0,
	`ownerPercentage` int NOT NULL DEFAULT 90,
	`commissionPercentage` int NOT NULL DEFAULT 10,
	`dueDay` int NOT NULL,
	`depositAmount` int DEFAULT 0,
	`guaranteeType` enum('caucao','fiador','seguro','nenhum'),
	`status` enum('ativo','encerrado','inadimplente','em_renovacao') NOT NULL DEFAULT 'ativo',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` int,
	CONSTRAINT `rental_contracts_id` PRIMARY KEY(`id`),
	CONSTRAINT `rental_contracts_contractNumber_unique` UNIQUE(`contractNumber`)
);
--> statement-breakpoint
CREATE TABLE `tenants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`documentNumber` varchar(20) NOT NULL,
	`email` varchar(320),
	`phone` varchar(20),
	`whatsapp` varchar(20),
	`occupation` varchar(100),
	`monthlyIncome` int,
	`companyName` varchar(255),
	`references` text,
	`notes` text,
	`active` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tenants_id` PRIMARY KEY(`id`)
);
